version: 2
type: Deployment
name: fastpass
registry_host: quay.io
registry_user: jwaldrip
ingress:
  tls: true
  host: fastpass.rocks
containers:
  server:
    healthcheck: true
    ports:
      http: 3000
