version: 2
type: Deployment
name: fastpass

{{#env.DOCKER_USERNAME}}
image_pull_secrets:
  - server: quay.io
    username: {{ env.DOCKER_USERNAME }}
    password: {{ env.DOCKER_PASSWORD }}
{{/env.DOCKER_USERNAME}}

context: gke_waldrip-net_us-central1-a_waldrip-net

volumes:
  store: 10Gi

registry_host: quay.io
registry_user: jwaldrip
ingress:
  tls: true
  host: fastpass.rocks
containers:
  server:
    volumes:
      store: /store
    command:
      - ./bin/fastpass
      - server
      - --fs=/store
    healthcheck: true
    ports:
      http: 3000
